
TRANSACTION;
CREATE TABLE goods(
	CODE VARCHAR(10) PRIMARY KEY,
	NAME VARCHAR(30),
	price INT,
	stock INT,
	category VARCHAR(20)
);

CREATE TABLE `ORDER`(
	NO INT PRIMARY key,
	customer VARCHAR(10),
	productCode VARCHAR(10) REFERENCES goods(CODE),
	amount INT,
	iscanceled BOOL
);

DROP TABLE `order`;
DROP TABLE goods;
ROLLBACK;
COMMIT;
